### ISSUE TITLE
How to implement?

### ISSUE THREAD

**Issue by landlord101** [miguel5612/ThermistorLibrary#18]
I am able to read temp with Arduino but how to pass this information to marlin, what are the connections of Arduino with the 3d printer motherboard and what changes do I need to do in marlin except for configuration changes?

**Comment by miguel5612** [comment]
Hello!,

The first step is to configure the libraries from the configuration.h file.

The second is the connections, which are explicit in the readme.

The final step is to load the code in your arduino and test.

I remain attentive to any questions :)
