### ISSUE TITLE
What is sensor 80?

### ISSUE THREAD

**Issue by chupocro** [miguel5612/ThermistorLibrary#3]
Hi,

what is the meaning of sensor 80 in:

`#define TEMP_SENSOR_0 80 // This is thermistor 0`

in **Configuration.h**?

The number 80 is not on the list.

**Comment by miguel5612** [comment]
**80** means an **3950 Thermistor**, see on readme.md:

80 : 3950 thermistor 100K - 4k7 Pull up and 10Uf Capacitor

 1k ohm pullup tables - This is atypical, and requires changing out the 4.7k pullup for 1k.
                      (but gives greater accuracy and more stable PID)

On configuration.h you can configure 4 types of sensor, and on the program declaration you can select the number of type changing between (0-3):
thermistor therm1(A0,0);  // Analog Pin which is connected to the 3950 temperature sensor, and 0 represents TEMP_SENSOR_0 (see configuration.h for more information).
