### ISSUE TITLE
Maximum number of sensors?

### ISSUE THREAD

**Issue by chupocro** [miguel5612/ThermistorLibrary#4]
There is a note:

> Supports any number of thermistors, the only thing that limits you is the number of analog inputs your arduino card has

However, by looking at **Configuration.h**, **Conditionals.h** and **Thermistortables.h** it seems as only 4 thermistors can be used without changing the code?

**Comment by miguel5612** [comment]
Only four types of sensor for each arduino board, you select what type of sensor are you using on the second parameter (0 - 3):
thermistor therm1(A0,0);

**Comment by miguel5612** [comment]
you can connect as many sensors as your development card has analog inputs and your program memory capacity supports it.
