### ISSUE TITLE
library.properties version is outdated

### ISSUE THREAD

**Issue by postpersonality** [miguel5612/ThermistorLibrary#5]
Hi,

The Arduino Library Manager installs version `1.0.3` dated Aug 2019. Can you please update `library.properties` with the current `1.0.4` version?

Thanks!

**Comment by atsushi1** [comment]
Ditto! I spent a day trying to figure out why the library I installed through the Arduino Library manager couldn't find <thermistor.h>.  I finally deleted the library and installed from a zip file, here, and it worked...

Thank you for this library! It is SO helpful!

**Comment by miguel5612** [comment]
Release 1.0.5 is Ok.
